import os
import requests
import json
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL", "https://azpvcqpnecljsosamnot.supabase.co")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")

headers = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json"
}

# Test checking existing tables
resp = requests.get(f"{SUPABASE_URL}/rest/v1/", headers=headers)
print("OpenAPI Paths:", list(json.loads(resp.text).get("paths", {}).keys()))

# Test creating table via query or checking rpc
sql_statements = [
    """
    CREATE EXTENSION IF NOT EXISTS vector;
    """,
    """
    CREATE TABLE IF NOT EXISTS raw_comments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        platform VARCHAR(50) NOT NULL,
        group_or_page VARCHAR(255),
        author VARCHAR(255),
        content TEXT NOT NULL,
        comment_created_at TIMESTAMP,
        crawled_at TIMESTAMP DEFAULT NOW(),
        status VARCHAR(50) DEFAULT 'pending'
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS insights (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        comment_id BIGINT REFERENCES raw_comments(id) ON DELETE CASCADE,
        spending_category VARCHAR(100),
        target_bank VARCHAR(100),
        target_card VARCHAR(100),
        intent VARCHAR(100),
        confidence_score FLOAT DEFAULT 1.0,
        created_at TIMESTAMP DEFAULT NOW()
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS card_knowledge (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        card_name VARCHAR(100) NOT NULL,
        bank_name VARCHAR(100) NOT NULL,
        topic VARCHAR(100),
        content TEXT NOT NULL,
        embedding vector(1536),
        created_at TIMESTAMP DEFAULT NOW()
    );
    """
]

# Let's test if we can call SQL query API or SQL endpoint
print("Testing endpoints...")
# Check if management API or sql endpoint responds
for ep in ["/rest/v1/rpc/exec", "/pg_meta/v0/query", "/rest/v1/sql"]:
    r = requests.post(f"{SUPABASE_URL}{ep}", headers=headers, json={"query": sql_statements[1]})
    print(f"Endpoint {ep}: Status {r.status_code}, Response: {r.text[:200]}")
