-- Supabase / PostgreSQL Schema cho Hệ thống Insights & Zalo Bot RAG (ABF Test)

-- 1. Kích hoạt Extension Vector cho RAG Search
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Bảng lưu dữ liệu comment thô cào về từ TikTok, FB, Zalo (Bài toán 1)
CREATE TABLE IF NOT EXISTS raw_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(50) NOT NULL,          -- 'tiktok', 'facebook', 'zalo'
    group_or_page VARCHAR(255),             -- Tên group Zalo / tên trang TikTok/FB
    author VARCHAR(255),                    -- Tên người comment / Zalo user
    content TEXT NOT NULL,                  -- Nội dung comment/tin nhắn
    comment_created_at TIMESTAMP,           -- Thời gian comment trên nền tảng
    crawled_at TIMESTAMP DEFAULT NOW(),     -- Thời gian cào về DB
    status VARCHAR(50) DEFAULT 'pending'    -- 'pending', 'processed', 'error'
);

-- Index cho tìm kiếm & filter nhanh
CREATE INDEX IF NOT EXISTS idx_raw_comments_platform ON raw_comments(platform);
CREATE INDEX IF NOT EXISTS idx_raw_comments_status ON raw_comments(status);
CREATE INDEX IF NOT EXISTS idx_raw_comments_created_at ON raw_comments(comment_created_at);

-- 3. Bảng lưu kết quả trích xuất Insights từ AI/LLM (Bài toán 1)
CREATE TABLE IF NOT EXISTS insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT REFERENCES raw_comments(id) ON DELETE CASCADE,
    spending_category VARCHAR(100),         -- 'du_lich', 'mua_sam_online', 'tra_gop', 'rut_tien', 'an_uong', 'khac'
    target_bank VARCHAR(100),               -- 'VIB', 'VPBank', 'Techcombank', 'HSBC', 'MB', ...
    target_card VARCHAR(100),               -- 'Max Card', 'Travel Élite', 'StepUp', ...
    intent VARCHAR(100),                    -- 'hoi_dieu_kien', 'hoi_uu_dai', 'so_sanh_the', 'khac'
    summary TEXT,                           -- Tóm tắt 1-2 câu của AI về nhu cầu của khách hàng
    confidence_score FLOAT DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_insights_spending_category ON insights(spending_category);
CREATE INDEX IF NOT EXISTS idx_insights_target_bank ON insights(target_bank);
CREATE INDEX IF NOT EXISTS idx_insights_target_card ON insights(target_card);

-- 4. Bảng Vector Store lưu Knowledge Base phục vụ RAG Chatbot (Bài toán 2)
CREATE TABLE IF NOT EXISTS card_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_name VARCHAR(100) NOT NULL,        -- Dòng thẻ (VD: VIB Max Card)
    bank_name VARCHAR(100) NOT NULL,        -- Ngân hàng (VD: VIB)
    topic VARCHAR(100),                     -- 'dieu_kien_mo_the', 'uu_dai_hoan_tien', 'phi_thuong_nien'...
    content TEXT NOT NULL,                  -- Đoạn văn bản chi tiết
    embedding vector(1536),                 -- Vector embedding (OpenAI text-embedding-3-small)
    created_at TIMESTAMP DEFAULT NOW()
);

-- Index IVFFlat / HNSW cho Vector Similarity Search
CREATE INDEX IF NOT EXISTS idx_card_knowledge_embedding 
ON card_knowledge USING hnsw (embedding vector_cosine_ops);

-- 5. Function hỗ trợ RAG Similarity Search
CREATE OR REPLACE FUNCTION match_card_knowledge (
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.5,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id bigint,
  card_name varchar,
  bank_name varchar,
  topic varchar,
  content text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    card_knowledge.id,
    card_knowledge.card_name,
    card_knowledge.bank_name,
    card_knowledge.topic,
    card_knowledge.content,
    1 - (card_knowledge.embedding <=> query_embedding) AS similarity
  FROM card_knowledge
  WHERE 1 - (card_knowledge.embedding <=> query_embedding) > match_threshold
  ORDER BY card_knowledge.embedding <=> query_embedding
  LIMIT match_count;
$$;
